### PR TITLE
ci: Update submodules automatically before building packages

### PR DESCRIPTION
**Pull request by Sheape**
Changes:

- Update void-packages to [3288eca](https://github.com/void-linux/void-packages/tree/3288eca6bc925a036c3670553b1c35a0d4e55e67)
- Update submodules automatically before building packages [520d099](https://github.com/Sheape/voidlinux-repository/commit/520d0994e4212743d287278db6dbd6c77633c171)
> It only updates the submodule whenever there are new changes from void-packages or apindex

### CODE REVIEW

**Comment by thetredev** [comment]
I'll take a look into this later, am on my phone right now.

**Comment by thetredev** [comment]
LGTM, thanks!

**Comment by thetredev** [comment]
Ah, dang. Gotta revert the changes due to the error `remote: error: Changes must be made through a pull request. `: https://github.com/xdeb-org/voidlinux-repository/actions/runs/7369335515/job/20054532494

Which is what I wanna keep active for this repository.

**Comment by Sheape** [comment]
> Ah, dang. Gotta revert the changes due to the error `remote: error: Changes must be made through a pull request. `: https://github.com/xdeb-org/voidlinux-repository/actions/runs/7369335515/job/20054532494
> 
> Which is what I wanna keep active for this repository.

Ahh I see, imma take a look at permissions if it needs something. Not a big deal if this doesn't get into stream.

**Comment by thetredev** [comment]
Already reverted, no need to look it up. I think it's best to keep it on a PR / push to master basis.

**Pull request merged**
